### ISSUE TITLE
Controls should reference their query using `query =` rather than `sql =`

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-mod-oci-compliance#57]
It's simpler in code and readability to reference queries using the query = attribute rather than the sql = attribute.

This occurs throughout the mod, but as a specific example:

https://github.com/turbot/steampipe-mod-oci-compliance/blob/12beca96d5af01733cd080a18fb3e63474a4e178/cis_v110/section_1.sp#L83-L95

Could be changed from:
```
sql           = query.identity_user_customer_secret_key_age_90.sql
```

to:
```
query         = query.identity_user_customer_secret_key_age_90
```

**Comment by misraved** [comment]
Closed as a part of https://github.com/turbot/steampipe-mod-oci-compliance/pull/58
