### ISSUE TITLE
Support for steampipe check of a particular compartment

### ISSUE THREAD

**Issue by jurajsucik** [turbot/steampipe-mod-oci-compliance#73]
**Is your feature request related to a problem? Please describe.**
 steampipe check will not work if the account that is used for access has read permissions only to a particular compartment.

**Describe the solution you'd like**
steampipe check should be able to perform a check only in a particular compartment.

**Comment by cbruno10** [comment]
Hi @jurajsucik , can you please describe your use case in a bit more detail? Also, if you're getting any errors or unexpected results today, can you please share what benchmarks/controls you're running and the results/errors you're getting? Thanks!

**Comment by bigdatasourav** [comment]
Hey @jurajsucik, we're closing this issue as we have not heard back from you; please feel free to re-open if you face the issue again or want to share anything. Thanks!

**Comment by bigdatasourav** [comment]
Hey @jurajsucik, we're closing this issue as we have not heard back from you; please feel free to re-open if you face the issue again or want to share anything. Thanks!
