### ISSUE TITLE
When installing steampipe-mod-oci-compliance for OCI, AWS is installed too

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-mod-oci-compliance#88]
**Describe the bug**
When installing this mod, the compliance checks for AWS are available too. But I want OCI only. 

**Powerpipe version (`powerpipe -v`)**
Powerpipe v0.4.0

**Steampipe version (`steampipe -v`)**
Steampipe v0.23.2

**Plugin version (`steampipe plugin list`)**
```
$ steampipe plugin list
+--------------------------------------------------+---------+-------------+
| Installed                                        | Version | Connections |
+--------------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/oci@latest       | 0.36.0  | oci         |
| hub.steampipe.io/plugins/turbot/steampipe@latest | 0.10.0  | steampipe   |
+--------------------------------------------------+---------+-------------+
```

```
$ powerpipe mod list

local
├── github.com/turbot/steampipe-mod-oci-compliance@v0.12.0
├── github.com/turbot/steampipe-mod-oci-insights@v0.8.0
└── github.com/turbot/steampipe-mod-oci-thrifty@v0.11.0
```

**To reproduce**
```
sudo /bin/sh -c "$(curl -fsSL https://powerpipe.io/install/powerpipe.sh)"
powerpipe -v 

mkdir powerpipe-mods
cd powerpipe-mods

powerpipe mod init
powerpipe mod install github.com/turbot/steampipe-mod-oci-compliance

$ powerpipe server
```

**Expected behavior**
When installing OCI mods, I only expect OCI components when running powerpipe server

**Additional context**
Screenshot with AWS components listed, but never installed.
![screenshot_powerpipe_dashboard](https://github.com/turbot/steampipe-mod-oci-compliance/assets/56437524/67d1c766-161b-45bc-97ef-311a71cebf92)

**Comment by khushboo9024** [comment]
@martinberger-ch Apologies for the late reply. We tried the same on our end and did not encounter any issues. We were able to see only OCI components when running the `Powerpipe server`. Could you please try again and let us know if the issue persists?

**Comment by misraved** [comment]
Hi @martinberger-ch,

I hope all is well with you. I'm writing to follow up on this issue. Since we haven't received any updates or feedback from you in a while, we'll be closing this issue for now.

If you still need assistance or if you have any further questions, please feel free to reopen the issue or create a new one. We're always here to help!

Thank you for your understanding.
